/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2024.1.1.259.1
    Soft IP Version: 1.2.4
    2024 12 19 07:22:00
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pcie_1x (rxp_i, rxn_i, refclkp_i, refclkn_i, aux_clk_i, txp_o, txn_o,
    refret_i, rext_i, perst_n_i, rst_usr_n_i, clk_usr_i, clk_usr_o,
    u_pl_link_up_o, u_dl_link_up_o, u_tl_link_up_o, m_w_hready_i, m_w_hresp_i,
    m_w_hrdata_i, m_w_haddr_o, m_w_hburst_o, m_w_hmastlock_o, m_w_hprot_o,
    m_w_hsize_o, m_w_htrans_o, m_w_hwrite_o, m_w_hwdata_o, m_r_hready_i,
    m_r_hresp_i, m_r_hrdata_i, m_r_haddr_o, m_r_hburst_o, m_r_hmastlock_o,
    m_r_hprot_o, m_r_hsize_o, m_r_htrans_o, m_r_hwrite_o, m_r_hwdata_o,
    c_apb_pclk_i, c_apb_preset_n_i, c_apb_paddr_i, c_apb_psel_i,
    c_apb_penable_i, c_apb_pwrite_i, c_apb_pwdata_i, c_apb_prdata_o,
    c_apb_pready_o, c_apb_pslverr_o, int_normal_o, int_critical_o,
    user_aux_power_detected_i, user_transactions_pending_i)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rxp_i;
    input  rxn_i;
    input  refclkp_i;
    input  refclkn_i;
    input  aux_clk_i;
    output  txp_o;
    output  txn_o;
    input  refret_i;
    input  rext_i;
    input  perst_n_i;
    input  rst_usr_n_i;
    input  clk_usr_i;
    output  clk_usr_o;
    output  u_pl_link_up_o;
    output  u_dl_link_up_o;
    output  u_tl_link_up_o;
    input  m_w_hready_i;
    input  m_w_hresp_i;
    input  [31:0]  m_w_hrdata_i;
    output  [31:0]  m_w_haddr_o;
    output  [2:0]  m_w_hburst_o;
    output  m_w_hmastlock_o;
    output  [3:0]  m_w_hprot_o;
    output  [2:0]  m_w_hsize_o;
    output  [1:0]  m_w_htrans_o;
    output  m_w_hwrite_o;
    output  [31:0]  m_w_hwdata_o;
    input  m_r_hready_i;
    input  m_r_hresp_i;
    input  [31:0]  m_r_hrdata_i;
    output  [31:0]  m_r_haddr_o;
    output  [2:0]  m_r_hburst_o;
    output  m_r_hmastlock_o;
    output  [3:0]  m_r_hprot_o;
    output  [2:0]  m_r_hsize_o;
    output  [1:0]  m_r_htrans_o;
    output  m_r_hwrite_o;
    output  [31:0]  m_r_hwdata_o;
    input  c_apb_pclk_i;
    input  c_apb_preset_n_i;
    input  [31:0]  c_apb_paddr_i;
    input  c_apb_psel_i;
    input  c_apb_penable_i;
    input  c_apb_pwrite_i;
    input  [31:0]  c_apb_pwdata_i;
    output  [31:0]  c_apb_prdata_o;
    output  c_apb_pready_o;
    output  c_apb_pslverr_o;
    output  int_normal_o;
    output  int_critical_o;
    input  user_aux_power_detected_i;
    input  [3:0]  user_transactions_pending_i;
endmodule