[package]
name = "radio-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
android-auto = { version = "0.3.7", optional = true }
async-trait = "0.1.88"
bincode = {version = "2.0.1", features = ["serde"]}
bluetooth-rust = { version = "0.3.6", optional = true}
chrono = { version = "0.4.43", features = ["serde"] }
clap = { version = "4.5.38", features = ["derive"] }
cpal = "0.15.3"
csv = "1.4.0"
eframe = { version = "0.34.1", default-features = false, features = ["accesskit", "default_fonts", "wayland", "glow"] }
egui = { version = "0.34.1", features = ["serde"] }
egui_extras = { version = "0.34.1", features = ["all_loaders"] }
egui_plot = "0.35.0"
enum_dispatch = "0.3.13"
evdev = { version = "0.13.2", optional = true }
ffimage = "0.10.0"
ffimage_yuv = "0.10.0"
ffmpeg-next = { version = "8.0.0", optional = true }
futures-util = "0.3.32"
image = { version = "0.25.2", features = ["jpeg", "png"] }
json = "0.12.4"
libc = { version = "0.2.183", optional = true }
log = "0.4.27"
nix = { version = "0.31.2", features = ["mman", "poll", "ioctl"], optional = true }
openh264 = "0.8.1"
qrcode = { version = "0.14.1", optional = true}
rand = "0.10.0"
reqwest = { version = "0.13.2", features = ["stream"] }
ringbuf = "0.4.8"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.149"
simple_logger = "5.0.0"
swupdate-ipc = { path = "./swupdate-ipc", optional=true }
thiserror = { version = "2.0.18", optional = true}
tokio = { version = "1.40.0", features = ["full"] }
tokio-tungstenite = "0.28.0"
toml = "0.8.20"
uobradio-comms = { path = "./uobradio-comms" }
zbus = "5.13.2"
zvariant = "5.9.2"

[dependencies.service]
version = "0.2.2"
features = ["async", "serde", "prompt", "egui-prompt"]

[target.'cfg(target_os = "linux")'.dependencies]
gpiocdev = { version = "0.8.0", optional = true, features = ["async_tokio"] }
industrial-io = { version = "0.6.1", optional = true }
nmrs = { version = "2.0.0", optional = true }

[[bin]]
name = "radio_service"
path = "src/service.rs"

[[bin]]
name = "radio_gui"
path = "src/main.rs"

[features]
default = ["usb", "androidauto"]
ffmpeg = ["dep:ffmpeg-next", "dep:thiserror"]
evdev = ["dep:evdev"]
gpio = ["dep:gpiocdev"]
iio = ["dep:industrial-io"]
v4l2m2m = ["dep:nix", "dep:thiserror", "dep:libc"]
imxvpuapi2 = ["dep:thiserror", "dep:libc"]
usb = ["android-auto?/usb"]
wifi = ["dep:qrcode", "dep:nmrs", "uobradio-comms/wifi", "android-auto?/wireless"]
bluetooth = ["dep:bluetooth-rust", "uobradio-comms/bluetooth"]
androidauto = ["dep:android-auto", "uobradio-comms/androidauto"]
swupdate = ["dep:swupdate-ipc"]

#this patch is needed for the v1 certificate in the android-auto crate of src/cert.rs
[patch.crates-io]
rustls-webpki = { path = "./webpki" }