[package]
name = "radio-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
android-auto = { git = "https://github.com/uglyoldbob/android-auto.git", optional = true, branch = "plain" }
async-trait = "0.1.88"
bincode = {version = "2.0.1", features = ["serde"]}
bluetooth-rust = { git = "https://github.com/uglyoldbob/bluetooth-rust.git", optional = true}
eframe = { version = "0.31.1" }
egui_extras = { version = "0.31.1", features = ["all_loaders"] }
enum_dispatch = "0.3.13"
ffimage = "0.10.0"
ffimage_yuv = "0.10.0"
image = { version = "0.25.2", features = ["jpeg", "png"] } # Add the types you want support for
log = "0.4.27"
openh264 = "0.8.1"
qrcode = { version = "0.14.1", optional = true}
serde = {version = "1.0.219", features = ["derive"]}
simple_logger = "5.0.0"
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.20"
uobradio-comms = { path = "./uobradio-comms" }
wifi-rs = { git = "https://github.com/uglyoldbob/wifi-rs.git", version = "0.2.4", optional = true }

[dependencies.service]
git = "https://github.com/uglyoldbob/service.git"
features = ["async", "serde", "prompt", "egui-prompt"]

[[bin]]
name = "radio_service"
path = "src/service.rs"

[[bin]]
name = "radio_gui"
path = "src/main.rs"

[features]
default = ["wifi", "bluetooth", "androidauto"]
wifi = ["dep:qrcode", "dep:wifi-rs", "uobradio-comms/wifi"]
bluetooth = ["dep:bluetooth-rust", "uobradio-comms/bluetooth"]
androidauto = ["dep:android-auto", "uobradio-comms/androidauto"]