[package]
name = "uobradio-comms"
version = "0.1.0"
edition = "2021"

[dependencies]
android-auto = { version = "0.3.4", optional = true }
bincode = {version = "2.0.1", features = ["serde"]}
bluetooth-rust = { version = "0.2.4", optional = true}
egui = { version = "0.31.1" }
ffimage = "0.10.0"
ffimage_yuv = "0.10.0"
image = { version = "0.25.2", features = ["jpeg", "png"] } # Add the types you want support for
log = "0.4.27"
serde = {version = "1.0.219", features = ["derive"]}
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.20"

[target.'cfg(target_os = "linux")'.dependencies]
nmrs = { version = "2.0.0", optional = true }
v4l = { version = "0.14.0", features = ["v4l2"] }

[features]
default = []
wifi = ["dep:nmrs"]
bluetooth = ["dep:bluetooth-rust"]
androidauto = ["dep:android-auto"]
test = []
