[package]
name = "android-auto"
version = "0.1.0"
edition = "2024"

[dependencies]
android-auto-sys = { path = "../android-auto-sys", optional = true }
bluetooth-rust = { path = "../bluetooth", optional = true }
futures = "0.3.30"
log = "0.4.27"
protobuf = "3.7.2"
tokio = { version = "1.40.0", features = ["full"], optional = true }

[build-dependencies]
protobuf-codegen = "3.7.2"

[features]
default = ["wireless"]
wireless = ["dep:bluetooth-rust", "dep:tokio"]